name: CI

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8
      - name: Ruff
        run: ruff check .
      - name: Flake8
        run: flake8 .

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (test only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run unit tests
        run: pytest -q

  smoke:
    # Запускаем только если есть все нужные секреты
    if: ${{ secrets.BOT_TOKEN != '' && secrets.BITRIX_DOMAIN != '' && secrets.BITRIX_REST_PATH != '' && secrets.ZCB_API_KEY != '' }}
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BITRIX_DOMAIN: ${{ secrets.BITRIX_DOMAIN }}
      BITRIX_REST_PATH: ${{ secrets.BITRIX_REST_PATH }}
      ZCB_API_KEY: ${{ secrets.ZCB_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps for smoke
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run smoke test
        run: python scripts/smoke.py
